name: SignTestPlugin
main: io.github.satoshinm.SignTestPlugin.SignTestPlugin
version: ${version}
commands:
  signtest:
    description: Tests functionality related to signs
    usage: "Usage: '/signtest'"
